<?php

namespace AppBundle\Repository;

/**
 * ActivityEffortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityEffortRepository extends AbstractEntityRepository
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'activityEffort';
    }

    /**
     * {@inheritdoc}
     */
    protected function getFields()
    {
        return [
            'id' => 'id',
            'date' => 'date',
            'hours' => 'hours',
            'description' => 'description',
            'isTracking' => 'isTracking',
            'activity' => 'IDENTITY(entity.activity)',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListFilters()
    {
        return [
            'activity',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListSearchFields()
    {
        return [
            'title',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getParent()
    {
        return 'activity';
    }
}
