<?php

namespace AppBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends AbstractEntityRepository
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'activity';
    }

    /**
     * {@inheritdoc}
     */
    protected function getFields()
    {
        return [
            'id' => 'id',
            'title' => 'title',
            'description' => 'description',
            'package' => 'IDENTITY(entity.package)',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListFilters()
    {
        return [
            'package',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListSearchFields()
    {
        return [
            'title',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getParent()
    {
        return 'package';
    }
}
