<?php

namespace AppBundle\Repository;

/**
 * ActivityEffortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityEffortRepository extends \Doctrine\ORM\EntityRepository
{
}
