<?php

namespace AppBundle\Repository;

/**
 * ChargingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
