<?php

namespace AppBundle\Repository;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageRepository extends AbstractEntityRepository
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'package';
    }

    /**
     * {@inheritdoc}
     */
    protected function getFields()
    {
        return [
            'id' => 'id',
            'title' => 'title',
            'description' => 'description',
            'project' => 'IDENTITY(process.project)',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListFilters()
    {
        return [
            'project',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListSearchFields()
    {
        return [
            'title',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getParent()
    {
        return 'project';
    }
}
