<?php

namespace AppBundle\Repository;

/**
 * ProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessRepository extends AbstractEntityRepository
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'process';
    }
}
