<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Youshido\GraphQL\Parser\Ast\Field;
use Youshido\GraphQL\Parser\Ast\Query;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends AbstractEntityRepository
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'project';
    }

    /**
     * {@inheritdoc}
     */
    protected function getFields()
    {
        return [
            'id' => 'id',
            'title' => 'title',
            'startDate' => 'processes.startDate',
            'endDate' => 'processes.endDate',
            'budget' => 'processes.budget',
            'hours' => 'processes.hours',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListSearchFields()
    {
        return [
            'title',
        ];
    }
}
