<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractEntityRepository
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    protected function getFields()
    {
        return [
            'id' => 'id',
            'login' => 'login',
            'internalHourlyRate' => 'internalHourlyRate',
            'externalHourlyRate' => 'externalHourlyRate',
            'lastLogin' => 'lastLogin',
            'locked' => 'locked',
            'passwordForgotten' => 'passwordForgotten',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getListSearchFields()
    {
        return [
            'login',
        ];
    }
}
