<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTokenRepository extends AbstractEntityRepository
{
    /**
     * {@inheritdoc}
     */
    protected function getName()
    {
        return 'userToken';
    }

    /**
     * {@inheritdoc}
     */
    protected function getFields()
    {
        return [
            'id' => 'id',
            'name' => 'name',
            'token' => 'token',
            'expirationDate' => 'expirationDate',
            'user' => 'IDENTIFIER(entity.user)',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getParent()
    {
        return 'user';
    }
}
