<?php

namespace AppBundle\Repository;

/**
 * UserTimetrackingTimestampsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTimetrackingTimestampRepository extends \Doctrine\ORM\EntityRepository
{
}
