<?php

namespace AppBundle\Repository;

/**
 * UserTimetrackingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTimetrackingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
