prooph_service_bus:
  command_buses:
    todo_command_bus:
      plugins:
        - 'prooph_event_store_bus_bridge.transaction_manager'
      router:
        type: 'prooph_service_bus.command_bus_router'
        routes:
          'AppBundle\CQRS\Model\Project\Command\CreateProject': 'proophdo.project_create_handler'
          'AppBundle\CQRS\Model\Project\Command\DeleteProject': 'proophdo.project_delete_handler'

  event_buses:
    todo_event_bus:
      plugins:
        - 'prooph_service_bus.on_event_invoke_strategy'
      router:
        type: 'prooph_service_bus.event_bus_router'
        routes:
          'AppBundle\CQRS\Model\Project\Event\ProjectWasCreated':
            - 'proophdo.todo_projection.project_projector'
          'AppBundle\CQRS\Model\Project\Event\ProjectWasDeleted':
            - 'proophdo.todo_projection.project_projector'

services:
    proophdo.project_create_handler:
        class: AppBundle\CQRS\Model\Project\Handler\ProjectCreateHandler
        arguments: ['@project_collection']
    proophdo.project_delete_handler:
        class: AppBundle\CQRS\Model\Project\Handler\ProjectDeleteHandler
        arguments: ['@project_collection']
